e try
	"Ok\n" :print
catch
	"Catch should not be called\n" :print
	1 :exit
yrt


e try
	1 0 /
catch
	e f"Error: {}\n" :print
yrt

e try
	1 0 /
finally
	"finnaly fired correctly\n" :print
yrt

errorCatch false =
e try
	1 0 /
catch
	e f"Error: {}\n" :print
	errorCatch true =
finally
	"finnaly fired correctly\n" :print
yrt

errorCatch :assert
